import type { CSSProperties } from 'react';

/**
 * The shared look of the config screen's cards.
 *
 * Lives apart from ConfigPage because each card is its own component now, and
 * they have to stay visually identical — a card that drifts reads as a
 * different kind of control.
 */

export const configStyles: Record<string, CSSProperties> = {
  container: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(440px, 1fr))',
    alignItems: 'start',
    gap: 'var(--space-lg)',
    padding: 'var(--space-xl)',
    boxSizing: 'border-box' as const,
  },
  cardWrapper: {
    position: 'relative',
  },
  card: {
    backgroundColor: 'var(--surface-2)',
    borderRadius: 'var(--radius-lg)',
    padding: 'var(--space-lg)',
  },
  statusRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 'var(--space-lg)',
  },
  label: {
    fontSize: 'var(--font-base)',
    color: 'var(--text-secondary)',
    fontWeight: 600,
  },
  statusBadge: {
    fontSize: 'var(--font-sm)',
    color: 'var(--text-primary)',
    padding: '4px 12px',
    borderRadius: 'var(--radius-lg)',
    fontWeight: 600,
  },
  input: {
    width: '100%',
    padding: 'var(--space-md)',
    fontSize: 'var(--font-base)',
    backgroundColor: 'var(--surface-0)',
    border: '2px solid var(--border)',
    borderRadius: 'var(--radius-md)',
    color: 'var(--text-primary)',
    outline: 'none',
    boxSizing: 'border-box' as const,
    minHeight: '56px',
  },
  buttonRow: {
    display: 'flex',
    gap: 'var(--space-md)',
    marginTop: 'var(--space-md)',
    flexWrap: 'wrap' as const,
  },
  button: {
    padding: '0.75rem 1.5rem',
    fontSize: 'var(--font-base)',
    fontWeight: 600,
    border: 'none',
    borderRadius: 'var(--radius-md)',
    cursor: 'pointer',
    minHeight: '56px',
    minWidth: 'var(--tap-min)',
  },
  saveButton: {
    backgroundColor: 'var(--color-accent)',
    color: 'var(--text-primary)',
    flex: 1,
  },
  deleteButton: {
    backgroundColor: 'var(--surface-3)',
    color: 'var(--color-danger)',
  },
  deleteButtonConfirm: {
    backgroundColor: 'var(--color-danger)',
    color: '#fff',
  },
  presetRow: {
    display: 'flex',
    gap: '2px',
    borderRadius: 'var(--radius-md)',
    overflow: 'hidden',
    marginBottom: 'var(--space-md)',
  },
  presetButton: {
    flex: 1,
    padding: 'var(--space-md)',
    fontSize: 'var(--font-base)',
    fontWeight: 600,
    backgroundColor: 'var(--surface-0)',
    color: 'var(--text-muted)',
    border: 'none',
    cursor: 'pointer',
    minHeight: 'var(--tap-sm)',
    fontFamily: 'inherit',
  },
  presetButtonActive: {
    flex: 1,
    padding: 'var(--space-md)',
    fontSize: 'var(--font-base)',
    fontWeight: 600,
    backgroundColor: 'var(--color-accent)',
    color: 'var(--text-primary)',
    border: 'none',
    cursor: 'pointer',
    minHeight: 'var(--tap-sm)',
    fontFamily: 'inherit',
  },
  settledValue: {
    fontSize: 'var(--font-md)',
    fontWeight: 700,
    color: 'var(--text-primary)',
    padding: 'var(--space-sm) 0 var(--space-md)',
  },
  blockedNotice: {
    fontSize: 'var(--font-base)',
    lineHeight: 1.5,
    color: 'var(--text-primary)',
    padding: 'var(--space-md)',
    marginBottom: 'var(--space-md)',
    backgroundColor: 'var(--surface-0)',
    borderRadius: 'var(--radius-md)',
    borderLeft: '3px solid var(--color-warning)',
  },
  // House pattern for destructive actions: default state is muted with danger
  // text, the pending state is solid danger. No confirmation dialog.
  dangerButton: {
    minHeight: 'var(--tap-min)',
    width: '100%',
    padding: '0 var(--space-lg)',
    fontSize: 'var(--font-md)',
    fontWeight: 700,
    fontFamily: 'inherit',
    color: 'var(--color-danger)',
    backgroundColor: 'var(--surface-3)',
    border: '2px solid var(--color-danger)',
    borderRadius: 'var(--radius-md)',
    cursor: 'pointer',
  },
  dangerButtonConfirm: {
    minHeight: 'var(--tap-min)',
    width: '100%',
    padding: '0 var(--space-lg)',
    fontSize: 'var(--font-md)',
    fontWeight: 700,
    fontFamily: 'inherit',
    color: '#ffffff',
    backgroundColor: 'var(--color-danger)',
    border: '2px solid var(--color-danger)',
    borderRadius: 'var(--radius-md)',
    cursor: 'pointer',
  },
  envHint: {
    fontSize: 'var(--font-sm)',
    color: 'var(--text-muted)',
    lineHeight: 1.5,
    marginBottom: 'var(--space-md)',
    padding: '0.75rem var(--space-md)',
    backgroundColor: 'var(--surface-0)',
    borderRadius: 'var(--radius-md)',
    borderLeft: '3px solid var(--color-accent)',
  },
  toggleButton: {
    position: 'relative' as const,
    width: '72px',
    height: '40px',
    borderRadius: '20px',
    border: 'none',
    cursor: 'pointer',
    transition: 'background-color 0.2s ease',
    padding: 0,
    minHeight: '40px',
  },
  toggleKnob: {
    display: 'block',
    width: '32px',
    height: '32px',
    borderRadius: '50%',
    backgroundColor: '#ffffff',
    transition: 'transform 0.2s ease',
    margin: '4px',
  },
  toggleLabel: {
    fontSize: '1rem',
    color: '#cccccc',
    marginTop: '0.5rem',
    marginBottom: '0.75rem',
  },
};
